apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  superUserPassword: {{ .Values.superUserPassword }}
  replicationUserPassword: {{ .Values.replicationUserPassword }}
